(auLoadCLF)
(setFormField "Load CLF File" "Load CLF File Without Timing Related Information" "1")
(setFormField "Load CLF File" "Library Name" (getenv "SRAM_MW_LIB"))
(setFormField "Load CLF File" "CLF File Name" (getenv "SRAM_CLF"))
(formOK "Load CLF File")

(auLoadCLF)
(setFormField "Load CLF File" "Load CLF File Without Timing Related Information" "1")
(setFormField "Load CLF File" "Library Name" (getenv "STD_CELL_MW_LIB"))
(setFormField "Load CLF File" "CLF File Name" (getenv "STD_CELL_CLF"))
(formOK "Load CLF File")
(exit)
